server:
  port: 8085
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://EMARKET-ORDERS
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://EMARKET-PAYMENTS
          predicates:
            - Path=/payment/**  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost